### ISSUE TITLE
Inconsistent live API examples documentation on `createSubscription`

### ISSUE THREAD

**Issue by arnisjuraga** [stripe-samples/subscription-with-fixed-price#4]
in API documentation "short" example, `createSubscription` is called passing `object` with three attributes, but in an example function definition - it's defined with 3 parameters

 https://stripe.com/docs/billing/subscriptions/fixed-price#create-subscription

Defined with 3 parameters:
```js
function createSubscription(customerId, paymentMethodId, priceId) { ...
```

Passing object:
```js
...
 createSubscription({
          customerId: customerId,
          paymentMethodId: result.paymentMethod.id,
          priceId: priceId,
        });
```

I a full example script, it's used with 3 attributes, so that would be preferred method.

https://github.com/stripe-samples/subscription-with-fixed-price/blob/master/client/script.js

**Comment by ctrudeau-stripe** [comment]
Fixed! thank you for flagging.
