### ISSUE TITLE
Trial period not showing up in the demo

### ISSUE THREAD

**Issue by Whateverinc** [stripe-samples/subscription-with-fixed-price#8]
I am currently testing the code and it all worked well until I got to the check out part. Instead of displaying the trial period, it says "Your subscription will start now". I see that in the [official documentation](https://stripe.com/docs/billing/subscriptions/fixed-price#collect-payment) that is in fact the case, but in the sandbox demo, the trial is shown.

**Comment by ctrudeau-stripe** [comment]
Hello, thank you for letting us know. I've updated the demo [0]. We have removed the free trial from this demo. If you'd like to add a free trial you can learn more [here](https://stripe.com/docs/billing/subscriptions/trials). 


[0] https://627ht.sse.codesandbox.io/
